from pathlib import Path
import re,json,html
from urllib.parse import urlencode,quote
from services_data import SERVICES
OUT=Path('outputs'); BASE='https://thepeeak.com'; E=html.escape
old=Path('work/before-refonte/index.html').read_text()
form=re.search(r'<form\b.*?</form>',old,re.S).group().replace('contact-form reveal','contact-form')
form=form.replace('Les champs marqués sont nécessaires.','WhatsApp est sélectionné par défaut. Pour l’e-mail, indiquez votre adresse. Les informations servent uniquement à traiter votre demande.')
form=form.replace('<label for="name">Votre nom','<label for="name">Votre nom *')
form=form.replace('<label for="email">Votre e-mail</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="255">','<label for="email">Votre e-mail <span class="optional">(facultatif sur WhatsApp)</span></label><input id="email" name="email" type="email" autocomplete="email" maxlength="255"><small class="field-hint">Nécessaire uniquement si vous choisissez l’envoi par e-mail.</small>')
form=form.replace('<label for="subject">Objet de la demande','<label for="subject">Objet de la demande *').replace('<label for="message">Votre projet','<label for="message">Votre projet *')
channel='''<div class="field full contact-channel"><span class="field-label" id="contact-channel-label">Comment souhaitez-vous nous contacter ?</span><div class="contact-channel-options" role="radiogroup" aria-labelledby="contact-channel-label"><label class="channel-option"><input type="radio" name="channel" value="whatsapp" checked><span><strong>WhatsApp</strong><small>Ouvrir une demande préremplie</small></span><b>Conseillé</b></label><label class="channel-option"><input type="radio" name="channel" value="email"><span><strong>E-mail</strong><small>Envoyer directement à THEPEEAK</small></span></label></div></div>'''
form=form.replace('<div class="field"><label for="email">',channel+'<div class="field"><label for="email">')
SERVICES[0]['faqs'][1]=('Combien de temps prend la création ?','THEPEEAK annonce un délai de 48 à 72 heures pour un site vitrine. Le point de départ, les contenus à fournir et les validations sont précisés au cadrage. Pour une plateforme complexe, le calendrier est défini après étude des fonctionnalités et des intégrations.')
SERVICES[0]['scope']+=' Pour un site vitrine, le délai annoncé est de 48 à 72 heures ; le calendrier des plateformes complexes est déterminé après étude.'
ORG={'@type':'Organization','@id':BASE+'/#organization','name':'THEPEEAK','url':BASE+'/','logo':BASE+'/thepeeak-logo-horizontal.png','email':'contact@thepeeak.com','telephone':'+22369656610','description':'Studio digital à Bamako, Mali : création web, branding, SEO, contenus et logiciels métier.','areaServed':{'@type':'Country','name':'Mali'}}
def head(title,desc,path,depth=0,graphs=[]):
 pre='../'*depth; url=BASE+('/' if path=='index.html' else '/'+path)
 graph=[ORG,{'@type':'WebSite','@id':BASE+'/#website','url':BASE+'/','name':'THEPEEAK','inLanguage':'fr','publisher':{'@id':BASE+'/#organization'}},{'@type':'WebPage','@id':url+'#webpage','url':url,'name':title,'description':desc,'inLanguage':'fr','isPartOf':{'@id':BASE+'/#website'}}]+graphs
 return f'''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)}</title><meta name="description" content="{E(desc)}"><link rel="canonical" href="{url}"><meta name="robots" content="index,follow,max-image-preview:large"><meta name="theme-color" content="#071c28"><meta property="og:type" content="website"><meta property="og:locale" content="fr_FR"><meta property="og:site_name" content="THEPEEAK"><meta property="og:title" content="{E(title)}"><meta property="og:description" content="{E(desc)}"><meta property="og:url" content="{url}"><meta property="og:image" content="{BASE}/thepeeak-logo-horizontal.png"><meta property="og:image:alt" content="THEPEEAK — Build what comes next"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="{pre}favicon.ico"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="{pre}assets/studio.css?v=20261003-contact-logo"><script type="application/ld+json">{json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False)}</script><script src="{pre}assets/studio.js?v=20261003-2" defer></script></head><body><a class="skip-link" href="#main">Aller au contenu</a>'''
def nav(depth=0):
 p='../'*depth
 return f'''<header class="site-header" id="top"><div class="wrap site-nav"><a href="{p}index.html" aria-label="THEPEEAK, accueil"><img class="site-logo" src="{p}thepeeak-logo-horizontal.png" width="146" height="68" alt="THEPEEAK"></a><button class="menu-button" aria-expanded="false" aria-controls="main-nav" type="button">Menu +</button><nav class="nav-links" id="main-nav" aria-label="Navigation principale"><a href="{p}index.html#approche">Approche</a><a href="{p}index.html#services">Expertises</a><a href="{p}realisations.html">Réalisations</a><a href="{p}sites-a-vendre.html">À vendre</a><a href="{p}guides/index.html">Guides</a><a href="{p}connexion.html">Espace client</a><a class="nav-cta" href="{p}contact.html">Parlons du projet ↗</a></nav></div></header>'''
def footer(depth=0):
 p='../'*depth
 return f'''<footer class="site-footer"><div class="wrap"><div class="footer-grid"><div><a href="{p}index.html"><img class="site-logo" src="{p}thepeeak-logo-horizontal.png" width="146" height="68" alt="THEPEEAK, accueil" loading="lazy"></a><p>Un studio à Bamako pour donner du sens à votre marque, construire vos outils et faire avancer votre activité.</p></div><nav aria-label="Explorer le site"><h2>Explorer</h2><div class="footer-links"><a href="{p}index.html#services">Nos expertises</a><a href="{p}realisations.html">Réalisations</a><a href="{p}sites-a-vendre.html">Sites à vendre</a><a href="{p}guides/index.html">Guides pratiques</a><a href="{p}connexion.html">Espace client</a></div></nav><nav aria-label="Informations légales"><h2>Informations</h2><div class="footer-links"><a href="{p}legal.html#mentions">Mentions légales</a><a href="{p}legal.html#confidentialite">Confidentialité</a><a href="{p}legal.html#cookies">Cookies</a><a href="{p}legal.html#conditions">Conditions d’utilisation</a></div></nav><div><h2>Le prochain échange</h2><div class="footer-links"><a href="https://wa.me/22369656610?text=Bonjour%20THEPEEAK%2C%20je%20souhaite%20parler%20de%20mon%20projet." target="_blank" rel="noopener noreferrer">WhatsApp · +223 69 65 66 10 ↗</a><a href="mailto:contact@thepeeak.com">contact@thepeeak.com</a><a href="{p}contact.html">Décrire mon projet ↗</a></div><p>Bamako, Mali<br>Collaboration à distance possible.</p></div></div><div class="footer-bottom"><span>© <span data-year>2026</span> THEPEEAK. Tous droits réservés.</span><span>Build what comes next.</span><a href="#top">Retour en haut ↑</a></div></div></footer></body></html>'''
def contact_url(s,p='../',subject=None): return p+'contact.html?'+urlencode({'service':s['slug'],'subject':subject or 'Demande de devis — '+s['name']})
def wa(s): return 'https://wa.me/22369656610?text='+quote('Bonjour THEPEEAK, je souhaite échanger sur votre service '+s['name']+'. Mon projet : ')
def ctas(s,p='../'): return f'<div class="actions"><a class="btn" href="{wa(s)}" target="_blank" rel="noopener noreferrer">Continuer sur WhatsApp <span>↗</span></a><a class="btn secondary" href="{E(contact_url(s,p))}">Autre moyen de contact <span>↗</span></a></div>'
def faq_markup(faqs): return '<div class="faq">'+''.join(f'<details><summary>{E(q)}</summary><p>{E(a)}</p></details>' for q,a in faqs)+'</div>'
def faq_schema(faqs): return {'@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in faqs]}
def breadcrumb_schema(name,url,mid=None):
 items=[{'@type':'ListItem','position':1,'name':'Accueil','item':BASE+'/'}]
 if mid: items.append({'@type':'ListItem','position':2,'name':mid[0],'item':BASE+'/'+mid[1]})
 items.append({'@type':'ListItem','position':len(items)+1,'name':name,'item':url})
 return {'@type':'BreadcrumbList','itemListElement':items}
def art(s):
 i=s['number']; caption='<span class="art-caption">Illustration de notre approche · THEPEEAK</span>'
 if i=='01': v='<div class="browser-demo"><div class="browser-chrome"><i></i><i></i><i></i></div><div class="browser-content"><small>VOTRE ENTREPRISE</small><strong>Une présence.<br>Un vrai point<br>de départ.</strong><div class="mock-lines"></div><span class="mock-button">Parlons de votre projet ↗</span></div></div>'
 elif i=='02': v='<div class="funnel-row">01 · Une question <span>Rechercher ↗</span></div><div class="funnel-row">02 · Une réponse <span>Comprendre ↗</span></div><div class="funnel-row">03 · Une rencontre <span>Contacter ↗</span></div>'
 elif i=='03': v='<span class="kicker">Du caractère. De la cohérence.</span><div class="brand-specimen">Aa.<br>THE NEXT.</div><div class="brand-swatches"><i></i><i></i><i></i></div>'
 elif i=='04': v='<span class="kicker">Un suivi qui se documente</span><div class="ops-row">Sauvegarder <span>Préparer</span></div><div class="ops-row">Mettre à jour <span>Contrôler</span></div><div class="ops-row">Restaurer <span>Documenter</span></div><div class="ops-row">Faire évoluer <span>Planifier</span></div>'
 elif i=='05': v='<span class="kicker">Du premier regard à l’action</span><div class="story-frames"><div class="story-frame">01<br>Attirer</div><div class="story-frame">02<br>Raconter</div><div class="story-frame">03<br>Inviter</div></div>'
 else:v='<span class="kicker">Exemple de parcours métier</span><div class="workflow-step">Une demande arrive</div><div class="workflow-step">La bonne équipe la prend en charge</div><div class="workflow-step">Le client suit son dossier ↗</div>'
 return '<div class="service-art" aria-hidden="true">'+v+caption+'</div>'
for s in SERVICES:
 url=BASE+'/services/'+s['slug']+'.html'
 schema=[{'@type':'Service','@id':url+'#service','name':s['name'],'serviceType':s['name'],'url':url,'description':s['intro'],'provider':{'@id':BASE+'/#organization'},'areaServed':{'@type':'Country','name':'Mali'}},breadcrumb_schema(s['name'],url),faq_schema(s['faqs'])]
 body=head(s['seo'],s['desc'],'services/'+s['slug']+'.html',1,schema).replace('<body>', '<body data-service="'+s['slug']+'">')+nav(1)
 body+=f'''<main id="main"><section class="hero service-hero"><div class="wrap"><nav class="breadcrumb" aria-label="Fil d’Ariane"><a href="../index.html">Accueil</a><span>/</span><a href="../index.html#services">Expertises</a><span>/ {E(s['short'])}</span></nav><div class="hero-layout"><div class="hero-copy"><span class="kicker">{s['number']} / {s['code']} · Studio digital à Bamako</span><h1>{s['title']}</h1><p class="intro">{E(s['intro'])}</p>{ctas(s)}</div>{art(s)}</div></div></section><nav class="service-subnav" aria-label="Sur cette page"><div class="wrap"><a href="#besoin">Votre besoin</a><a href="#solutions">Les solutions</a><a href="#livrables">Les livrables</a><a href="#methode">Le déroulement</a><a href="#questions">Vos questions</a></div></nav>
<section class="section" id="besoin"><div class="wrap problem-grid"><div data-reveal><span class="kicker">Partir du réel</span><h2>{E(s['problem'])}</h2></div><div class="problem-right" data-reveal><h3>Ce que cela change au quotidien</h3><p>{E(s['impact'])}</p><h3>Le travail à engager</h3><p>{E(s['solution'])}</p></div></div></section>
<section class="section approach" id="solutions"><div class="wrap"><div class="section-heading"><span class="kicker">Choisir le bon périmètre</span><h2>Une réponse à votre <em>besoin.</em></h2></div><div class="options-grid">'''
 for a,b,c in s['options']: body+=f'<article class="option-card" data-reveal><small>{E(a)}</small><h3>{E(b)}</h3><p>{E(c)}</p><a class="text-link" href="{E(contact_url(s,subject=b+" — "+s["name"]))}">Discuter de cette solution ↗</a></article>'
 body+=f'''</div></div></section><section class="section dark" id="livrables"><div class="wrap deliver-grid"><div data-reveal><span class="kicker">Ce que vous obtenez</span><h2>Du concret,<br>du début à la <em>suite.</em></h2><p class="intro">Les livrables retenus sont détaillés dans votre proposition. Vous savez ce qui est réalisé, ce que vous validez et ce qui peut évoluer.</p><div class="deliver-note"><strong>Budget & périmètre</strong><p>{E(s['scope'])}</p></div></div><div data-reveal><ul class="deliver-list">{''.join('<li>'+E(x)+'</li>' for x in s['deliver'])}</ul>{ctas(s)}</div></div></section>
<section class="section" id="methode"><div class="wrap"><span class="kicker">Le déroulement</span><h2>Des étapes claires.<br>Des décisions <em>partagées.</em></h2><div class="process-grid">'''
 for i,(t,d) in enumerate(s['steps'],1): body+=f'<article class="process-step" data-reveal><span class="step-no">0{i}</span><h3>{E(t)}</h3><p>{E(d)}</p></article>'
 body+=f'''</div><div class="brief-box"><div><h3>Pour bien démarrer</h3><p>{E(s['prepare'])}</p></div><div><h3>Ce que nous pouvons suivre</h3><p>{E(s['measure'])}</p></div></div><div class="actions"><a class="text-link" href="../realisations.html">Découvrir les réalisations publiées ↗</a></div></div></section>
<section class="section approach" id="questions"><div class="wrap faq-grid"><div><span class="kicker">Les réponses avant le devis</span><h2>Parlons aussi<br>des <em>détails.</em></h2><p class="intro">{E(s['name'])} à Bamako et au Mali : les points à clarifier pour démarrer sereinement.</p></div>{faq_markup(s['faqs'])}</div></section>
<section class="section"><div class="wrap"><span class="kicker">Construire un ensemble cohérent</span><h2>Et pour la suite ?</h2><div class="related-grid">'''
 for other in [x for x in SERVICES if x!=s][:3]:body+=f'<a class="related-card" href="{other["slug"]}.html">{E(other["short"])} <em>↗</em></a>'
 body+=f'''</div><a class="text-link" href="../guides/index.html">Nos guides pour préparer votre projet ↗</a></div></section><section class="closing"><div class="wrap row"><div><span class="kicker">Votre prochaine étape</span><h2>Faisons le point<br>sur votre <strong>projet.</strong></h2></div><div><p>Votre contexte, vos priorités, vos contraintes.<br>Commençons par ce qui compte pour vous.</p>{ctas(s)}</div></div></section></main>'''+footer(1)
 (OUT/'services'/f'{s["slug"]}.html').write_text(body)
HOMEFAQ=[('Quels services propose THEPEEAK à Bamako ?','THEPEEAK accompagne la création de sites web, le SEO et le marketing digital, le branding, l’hébergement et la maintenance, la création de visuels et vidéos IA, ainsi que les logiciels métier et l’automatisation.'),('En combien de temps pouvez-vous créer un site vitrine ?','Le délai annoncé est de 48 à 72 heures pour un site vitrine. Les contenus nécessaires, les validations et le point de départ sont précisés au cadrage. Le délai des plateformes complexes est déterminé après étude.'),('Comment obtenir un devis ?','Choisissez une expertise ou décrivez votre besoin via le formulaire ou WhatsApp. Nous précisons les livrables, les options, les frais récurrents et le calendrier avant de proposer un devis.'),('Peut-on travailler ensemble à distance ?','Oui. Les échanges et les validations peuvent se faire à distance. Pour un projet au Sénégal, en Côte d’Ivoire ou au Niger, nous cadrons les usages locaux, les moyens de paiement et les contraintes avant de confirmer le périmètre.'),('Le référencement garantit-il des clients ?','Non. Le référencement peut améliorer la visibilité et la compréhension de vos offres, mais les demandes dépendent aussi de votre marché, de votre réputation et de votre capacité à convertir. Nous cherchons des progrès mesurables, sans garantir de classement ni de ventes.')]
peak='''<div class="hero-art" aria-hidden="true"><div class="orbit"></div><div class="orbit two"></div><span class="art-note top">THEPEEAK / Next perspective</span><svg class="peak-mark" viewBox="0 0 550 500" fill="none"><defs><linearGradient id="face" x1="160" y1="70" x2="390" y2="430" gradientUnits="userSpaceOnUse"><stop stop-color="#f9faf5"/><stop offset="1" stop-color="#607b86"/></linearGradient><linearGradient id="fire" x1="270" y1="200" x2="460" y2="420"><stop stop-color="#ffad55"/><stop offset="1" stop-color="#ff5710"/></linearGradient></defs><path d="M40 414L278 70L370 245L246 422H172L289 256L275 218L133 414H40Z" fill="url(#face)"/><path d="M278 70L304 192L275 218L289 256L370 245L278 70Z" fill="#fff" opacity=".75"/><path d="M333 296L379 227L491 421H401L333 296Z" fill="url(#fire)"/><path d="M333 296L401 421L370 315L379 227L333 296Z" fill="#de4200"/><path d="M74 455H496M279 35V462" stroke="#d9e2df" stroke-opacity=".12" stroke-dasharray="3 7"/><circle cx="491" cy="421" r="6" fill="#ff6b19"/></svg><span class="scroll-cue">↓</span><span class="art-note bottom">De l’idée à l’impact.</span></div>'''
s=head('Agence digitale à Bamako : web, SEO, branding | THEPEEAK','THEPEEAK, studio digital à Bamako : sites vitrines en 48 à 72 h, branding, SEO, vidéos IA et logiciels métier. Livrables clairs, accompagnement sur devis.','index.html',graphs=[faq_schema(HOMEFAQ)])+nav()
s+=f'''<main id="main"><section class="hero home-hero"><div class="wrap"><div class="hero-layout"><div class="hero-copy"><span class="kicker">Studio digital · Bamako, Mali</span><h1>Votre prochain<br>cap commence<br><em>ici.</em></h1><p class="intro">Une marque qui se distingue. Un site qui donne envie de vous contacter. Des outils qui simplifient le travail. Construisons ce qui fait avancer votre entreprise.</p><div class="actions"><a class="btn" href="#services">Explorer nos expertises <span>↗</span></a><a class="btn secondary" href="contact.html">Parlons du projet <span>↗</span></a></div></div>{peak}</div><div class="hero-meta"><span><b>01 — 06</b> / Expertises connectées</span><span><b>48–72 h</b> / Sites vitrines · périmètre à cadrer</span><span><b>Build what comes next.</b> ↓</span></div></div></section>
<section class="section approach" id="approche"><div class="wrap approach-grid"><div data-reveal><span class="kicker">Notre approche</span><h2>Le bon cap.<br>Le bon design.<br><em>Le bon outil.</em></h2><p class="intro">Votre projet commence par une question simple : qu’est-ce qui doit changer pour vos clients ou pour votre équipe ?</p><div class="actions"><a class="text-link" href="guides/preparer-projet-digital.html">Préparer notre premier échange ↗</a></div></div><div class="approach-items">'''
for i,(t,d) in enumerate([('Comprendre avant de créer','Vos publics, votre activité et l’action attendue. Un besoin clair rend chaque décision plus utile.'),('Concevoir un ensemble cohérent','Les mots, l’identité et le parcours se répondent. Vos clients comprennent où ils sont et quoi faire.'),('Construire avec vous','Des étapes de validation, des livrables définis et un suivi du périmètre pour avancer ensemble.'),('Préparer la suite','Des accès, de la documentation et un accompagnement à définir pour garder la maîtrise après livraison.')],1):s+=f'<article class="approach-item" data-reveal><span class="step-no">0{i}</span><div><h3>{t}</h3><p>{d}</p></div></article>'
s+='''</div></div></section><section class="section" id="services"><div class="wrap"><div class="section-heading row"><div><span class="kicker">Nos expertises · 01—06</span><h2>Six façons de<br>faire <em>avancer les choses.</em></h2></div><p>Une expertise pour un besoin précis, ou plusieurs pour construire un ensemble. Chaque service détaille ses livrables, son déroulement et ses limites.</p></div><div class="services-grid">'''
for v in SERVICES:s+=f'<a class="service-card" data-reveal href="services/{v["slug"]}.html"><div class="card-top"><span>{v["number"]} / {v["code"]}</span><span>↗</span></div><h3>{v["short"]}</h3><p>{E(v["solution"])}</p><span class="card-link">{v["verb"]} avec THEPEEAK ↗</span></a>'
s+='''</div></div></section><section class="section dark" id="orientation"><div class="wrap diagnostic"><div data-reveal><span class="kicker">Par où commencer ?</span><h2>Partons de<br>votre <em>priorité.</em></h2><p class="intro">Vous n’avez pas besoin de connaître le nom de la prestation. Choisissez ce que vous souhaitez améliorer : nous vous indiquons un premier point de départ.</p></div><div class="chooser"><label for="need-picker">Aujourd’hui, je souhaite…</label><select id="need-picker">'''
needs=['Présenter mon activité ou vendre en ligne','Être trouvé et recevoir plus de demandes','Clarifier mon image de marque','Faire suivre et entretenir mon site','Créer des visuels ou une vidéo','Simplifier le travail de mon équipe']
for v,n in zip(SERVICES,needs):s+=f'<option value="{v["slug"]}" data-title="{E(v["short"])}" data-description="{E(v["solution"])}">{n}</option>'
s+='''</select><div class="choice-result" aria-live="polite"><span class="kicker">Une première piste</span><h3 id="need-title">Web & mobile</h3><p id="need-description">Un site structuré autour de votre offre et de la prise de contact.</p><div class="actions"><a class="btn" id="need-service" href="services/creation-site-web.html">Voir cette expertise ↗</a><a class="btn secondary" id="need-contact" href="contact.html">Décrire mon besoin ↗</a></div></div></div></div></section>
<section class="section" id="realisations"><div class="wrap"><div class="section-heading row"><div><span class="kicker">Le travail prend forme</span><h2>Les réalisations.</h2></div><a class="text-link" href="realisations.html">Toutes les réalisations ↗</a></div><div class="work-grid" id="home-work-list" aria-live="polite"><div class="work-empty">Chargement des projets publiés… <a href="realisations.html">Ouvrir le portfolio ↗</a></div></div><noscript><p>Le portfolio interactif nécessite JavaScript. <a href="contact.html">Demander des exemples de réalisations.</a></p></noscript></div></section>
<section class="section approach" id="studio"><div class="wrap studio-split"><div data-reveal><span class="kicker">Le studio</span><div class="studio-word">BUILD<br>WHAT’S<br><span>NEXT.</span></div></div><div data-reveal><h2>De l’ambition.<br>Et les moyens<br>de lui donner <em>forme.</em></h2><p class="intro">THEPEEAK est un studio digital à Bamako. Nous rapprochons la stratégie, le design et la technologie pour accompagner les entreprises qui lancent une activité, revoient leur présence ou structurent leur croissance.</p><p class="intro">Le mobile, la clarté des offres et la facilité de contact sont au centre du travail. Pour les collaborations à distance au Sénégal, en Côte d’Ivoire ou au Niger, nous étudions les usages et les contraintes du projet.</p><div class="pill-row"><span class="pill">Périmètre défini</span><span class="pill">Validation par étapes</span><span class="pill">Livrables documentés</span></div><div class="actions"><a class="text-link" href="sites-a-vendre.html">Découvrir aussi les sites disponibles à la vente ↗</a></div></div></div></section>
<section class="section"><div class="wrap"><div class="section-heading row"><div><span class="kicker">Mieux comprendre, mieux décider</span><h2>Avant de <em>vous lancer.</em></h2></div><a class="text-link" href="guides/index.html">Tous les guides ↗</a></div>'''
GUIDES=[('budget-site-web-mali','01 / Création web','Budget d’un site : les bonnes questions.','Comparer des devis en regardant les livrables, les frais récurrents et les responsabilités.'),('seo-geo-mali','02 / Visibilité','SEO et GEO : ce qui compte vraiment.','Comprendre les moteurs, les réponses IA et ce que votre site peut améliorer.'),('preparer-projet-digital','03 / Méthode','Un brief qui fait gagner du temps.','Préparer les informations utiles pour une proposition adaptée à votre projet.')]
def guide_cards(p='guides/'):
 return '<div class="guide-grid">'+''.join(f'<article class="guide-card" data-reveal><small>{code}</small><h3>{title}</h3><p>{desc}</p><a class="text-link" href="{p}{slug}.html">Lire le guide ↗</a></article>' for slug,code,title,desc in GUIDES)+'</div>'
s+=guide_cards()+f'''</div></section><section class="section approach"><div class="wrap faq-grid"><div><span class="kicker">Avant le premier échange</span><h2>Vos questions.<br>Des réponses <em>claires.</em></h2></div>{faq_markup(HOMEFAQ)}</div></section><section class="section" id="contact"><div class="wrap contact-grid"><div><span class="kicker">Faisons connaissance</span><h2>Et si on parlait<br>de votre <em>prochain cap ?</em></h2><p class="intro">Décrivez votre activité, ce que vous souhaitez améliorer et vos contraintes. Nous pourrons préciser ensemble la bonne façon d’avancer.</p><div class="contact-direct"><a href="https://wa.me/22369656610?text=Bonjour%20THEPEEAK%2C%20je%20souhaite%20discuter%20de%20mon%20projet." target="_blank" rel="noopener noreferrer">WhatsApp · +223 69 65 66 10 ↗</a><a href="mailto:contact@thepeeak.com">contact@thepeeak.com ↗</a></div></div>{form}</div></section></main><dialog id="showcase-dialog" class="showcase-dialog" aria-label="Détail de la réalisation"><button type="button" class="dialog-close" aria-label="Fermer les détails">×</button><div id="showcase-dialog-content"></div></dialog>'''
backend='''<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.min.js" defer></script><script src="assets/supabase-config.js" defer></script><script src="assets/supabase-client.js" defer></script>'''
s+=backend+'<script src="assets/contact-form.js?v=20261003-whatsapp-resend" async></script><script src="assets/showcase.js" defer></script>'+footer()
(OUT/'index.html').write_text(s)
c=head('Contact & devis pour votre projet digital | THEPEEAK','Présentez votre projet à THEPEEAK : création web, SEO, branding, visuels ou logiciel métier. Contact à Bamako par formulaire, e-mail ou WhatsApp.','contact.html')+nav()+f'''<main id="main"><section class="section" id="contact"><div class="wrap contact-grid"><div><span class="kicker">Un premier échange</span><h1>Votre idée.<br>Notre prochain<br><em>projet ?</em></h1><p class="intro">L’objet et l’expertise restent modifiables. Partagez vos besoins et vos contraintes pour préparer une proposition adaptée.</p><div class="contact-direct"><a href="https://wa.me/22369656610" target="_blank" rel="noopener noreferrer">WhatsApp · +223 69 65 66 10 ↗</a><a href="mailto:contact@thepeeak.com">contact@thepeeak.com ↗</a></div><p class="intro">Sites vitrines : délai annoncé de 48 à 72 heures, avec conditions de démarrage précisées au cadrage. Plateformes complexes : calendrier à déterminer.</p></div>{form}</div></section></main>'''+backend+'<script src="assets/contact-form.js?v=20261003-whatsapp-resend" async></script>'+footer()
(OUT/'contact.html').write_text(c)
(OUT/'guides/index.html').write_text(head('Guides pour votre projet web, SEO et digital | THEPEEAK','Préparez votre projet digital : comprendre un devis de site web au Mali, distinguer SEO et GEO et rédiger un brief utile. Les guides THEPEEAK.','guides/index.html',1)+nav(1)+'<main id="main"><section class="page-intro"><div class="wrap"><span class="kicker">Les guides du studio</span><h1>Mieux comprendre.<br><em>Mieux décider.</em></h1><p class="intro">Des repères concrets pour préparer votre prochain projet, poser les bonnes questions et comparer les propositions.</p></div></section><section class="section"><div class="wrap">'+guide_cards('')+'</div></section></main>'+footer(1))
