from build_editorial import head,nav,footer,breadcrumb_schema,OUT,BASE,E
import json
ARTICLES=[
('budget-site-web-mali','Budget d’un site web au Mali : comment comparer les devis','Un devis de site web ne se compare pas seulement sur son total. Voici les livrables, les coûts récurrents et les responsabilités à examiner avant de choisir.',[
('perimetre','Commencer par l’usage, pas par le nombre de pages','''<p>Un site vitrine présente votre activité et facilite la prise de contact. Une boutique ajoute un catalogue, des commandes et des règles de paiement. Une plateforme peut gérer des comptes, des droits, des dossiers et des connexions avec d’autres outils. Ces projets ne demandent pas le même travail.</p><p>Avant de demander un prix, décrivez l’action principale attendue : un appel, une demande de devis, une réservation, un achat ou l’accès à un service. Listez ensuite les pages et les fonctions nécessaires à cette action. Les autres idées peuvent former une deuxième étape.</p><p>Chez THEPEEAK, les prix sont établis sur devis. Le délai annoncé pour un site vitrine est de 48 à 72 heures, avec le point de départ et les validations précisés au cadrage. Les plateformes complexes demandent un calendrier déterminé après étude.</p>'''),
('comparer','Les six lignes à comparer dans une proposition','''<table><thead><tr><th>Poste</th><th>Question à poser</th></tr></thead><tbody><tr><td>Contenus</td><td>Qui écrit les textes, prépare les photos et intègre les données ?</td></tr><tr><td>Design</td><td>Quelles pages sont maquettées et combien de validations sont prévues ?</td></tr><tr><td>Fonctionnalités</td><td>Quels formulaires, comptes, paiements et connexions sont compris ?</td></tr><tr><td>Référencement</td><td>Quelles optimisations techniques et éditoriales seront effectivement livrées ?</td></tr><tr><td>Livraison</td><td>Quels accès, fichiers et documents seront transmis ?</td></tr><tr><td>Suivi</td><td>Quelle maintenance est prévue et quelles évolutions seront facturées à part ?</td></tr></tbody></table><p>Deux devis de même montant peuvent couvrir des travaux très différents. Faites reformuler toute ligne trop générale, comme « SEO complet » ou « maintenance incluse », en opérations concrètes et vérifiables.</p>'''),
('recurrence','Distinguer la création des frais récurrents','''<p>Le domaine, l’hébergement, certaines licences, les outils d’envoi d’e-mails et la maintenance peuvent créer des coûts récurrents. Le budget publicitaire et les commissions d’un prestataire de paiement sont encore d’autres postes. Demandez qui les règle, à quelle fréquence et ce qui se passe en cas d’arrêt.</p><p>Un site peu coûteux à créer peut devenir difficile à maintenir si vous ne disposez pas des accès. Identifiez le titulaire du domaine, la personne responsable des renouvellements et les conditions de transfert des contenus.</p>'''),
('calendrier','Ce qui influence le calendrier','''<p>Un brief clair, des textes disponibles et des visuels autorisés facilitent le démarrage. À l’inverse, une traduction à produire, une connexion à un logiciel ou la validation d’un compte marchand peut allonger les étapes. Le calendrier doit intégrer les retours du client et les dépendances externes.</p><p>Pour une plateforme complexe, un prototype permet de vérifier les écrans et les règles avant de développer. Commencer par une version centrée sur un processus utile aide à décider des évolutions à partir d’un usage réel.</p>'''),
('decision','Préparer une demande de devis comparable','''<p>Envoyez le même brief aux prestataires : activité, public, objectif, pages, fonctions, contenus disponibles, contraintes et date souhaitée. Demandez une réponse séparant le socle, les options et les frais récurrents.</p><div class="article-callout"><strong>Le prochain pas</strong><p>Présentez votre besoin, même si vous ne connaissez pas encore toutes les fonctionnalités. Nous pouvons préciser le périmètre ensemble.</p><p><a href="../services/creation-site-web.html">Voir les livrables de création web</a> · <a href="../contact.html?service=creation-site-web&amp;subject=Devis%20site%20web">Demander un devis</a></p></div>''')]),
('seo-geo-mali','SEO et GEO : rendre vos offres faciles à trouver et à comprendre','Moteurs de recherche, réponses IA, contenus et mesure : les bases pour construire une présence utile, sans promesse de classement automatique.',[
('definitions','SEO et GEO : deux usages, un socle commun','''<p>Le référencement naturel, ou SEO, travaille l’accès, la compréhension et la pertinence de vos pages dans les moteurs. Le terme GEO désigne les efforts visant à rendre votre contenu compréhensible et potentiellement utilisable dans des réponses générées par l’IA.</p><p>Pour les fonctionnalités IA de Google Search, Google indique que les bonnes pratiques SEO restent applicables et qu’aucune optimisation spéciale supplémentaire n’est requise. Un contenu clair, accessible et cohérent reste donc un point de départ plus solide qu’une accumulation de balises.</p>'''),
('contenu','Répondre aux questions qui précèdent un achat','''<p>Une page de service utile permet au lecteur de comprendre à qui s’adresse la prestation, quel problème elle traite, ce qu’il recevra et ce qui n’est pas inclus. Elle explique le déroulement, les informations nécessaires, les critères de budget et les modalités de contact.</p><p>Ajoutez des réponses précises aux questions de vos prospects. Des exemples réels et autorisés peuvent illustrer le travail. Si vous utilisez un exemple fictif, présentez-le comme une illustration, sans le transformer en témoignage ou en résultat client.</p><p>Une FAQ complète une page bien structurée ; elle ne remplace pas le contenu principal. Les informations importantes doivent être présentes dans le texte visible et les données structurées doivent rester cohérentes avec ce texte.</p>'''),
('technique','Préparer l’accès et la compréhension des pages','''<p>Chaque page importante doit avoir une adresse stable, un titre explicite, une description adaptée et des liens depuis d’autres pages du site. La navigation et les appels à l’action doivent fonctionner sur téléphone. Un sitemap aide les moteurs à découvrir les URL que vous souhaitez faire explorer.</p><p>Les pages publiques de THEPEEAK fournissent leur texte dans le HTML : leur lecture ne dépend pas de l’exécution d’une application JavaScript. Les informations de marque et de service sont également décrites par des données structurées. Ces éléments aident à comprendre le site ; ils ne garantissent pas son indexation ou son classement.</p>'''),
('local','Être précis sur votre présence locale','''<p>Indiquez le vrai nom de votre entreprise, des coordonnées cohérentes et les services réellement proposés. À Bamako comme sur un autre marché, des informations exactes sont plus utiles qu’une liste répétitive de villes.</p><p>Une collaboration à distance au Sénégal, en Côte d’Ivoire ou au Niger ne signifie pas que vous possédez un bureau sur place. Les pages locales doivent apporter des informations propres au marché et décrire honnêtement votre mode d’intervention.</p>'''),
('mesurer','Suivre les demandes, pas seulement la visibilité','''<p>Search Console permet de suivre des requêtes, impressions et clics de recherche. Croisez ces informations avec les formulaires reçus, les échanges commerciaux et la qualité des demandes. Pour une campagne, des paramètres de suivi peuvent aider à identifier la source d’un contact.</p><p>Une comparaison utile tient compte du temps nécessaire à l’exploration, de la saisonnalité et des changements survenus dans votre activité. Une variation de position sur une requête isolée ne suffit pas à expliquer l’évolution des ventes.</p><div class="article-callout"><strong>Ce qu’aucun prestataire ne maîtrise</strong><p>La décision d’indexer, de classer ou de citer un site appartient aux moteurs. Un prestataire peut expliquer ses travaux, leurs priorités et les résultats observés, mais ne peut garantir chaque apparition.</p></div><p><a href="../services/marketing-seo-geo.html">Découvrir notre accompagnement SEO et GEO</a></p>'''),
('sources','Sources et mise à jour','''<p>Références officielles : <a href="https://developers.google.com/search/docs/appearance/ai-features" target="_blank" rel="noopener noreferrer">Google Search Central — fonctionnalités IA et site web</a> ; <a href="https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap" target="_blank" rel="noopener noreferrer">créer et soumettre un sitemap</a>. Guide préparé le 3 octobre 2026. Les recommandations peuvent évoluer avec les moteurs.</p>''')]),
('preparer-projet-digital','Préparer un brief digital : les informations qui font avancer le projet','Un brief simple permet de cadrer un site, une identité ou un logiciel. Voici les questions utiles pour transformer une idée en périmètre de travail.',[
('objectif','Décrire le changement attendu','''<p>Commencez par une phrase concrète : « Je souhaite que les prospects comprennent mes trois offres et demandent un devis », ou « Je veux que l’équipe suive chaque dossier sans recopier les informations ». Il s’agit d’exemples de formulation, pas de résultats déjà obtenus.</p><p>Précisez qui utilisera le résultat : prospects, clients, collaborateurs ou partenaires. Un site public et un outil interne peuvent partager une identité, mais leurs parcours répondent à des besoins différents.</p>'''),
('existant','Faire l’inventaire de ce qui existe','''<p>Rassemblez le site actuel, les supports commerciaux, les textes, le logo et les visuels que vous êtes autorisé à utiliser. Signalez les contenus à écrire, les traductions à prévoir et les éléments que vous souhaitez conserver.</p><p>Pour un logiciel, décrivez un dossier depuis son arrivée jusqu’à sa clôture. Identifiez les personnes qui interviennent, les validations et les exceptions. Utilisez des données fictives ou anonymisées lors des premiers échanges.</p>'''),
('priorites','Séparer le nécessaire de la suite','''<p>Classez vos besoins en trois ensembles : indispensable au lancement, utile après les premiers retours et idée à étudier plus tard. Ce classement facilite les arbitrages si une fonction exige beaucoup de temps ou dépend d’un prestataire externe.</p><p>Les connexions à un CRM, les paiements, le multilingue, la reprise de données et le fonctionnement hors ligne doivent être signalés tôt. Leur faisabilité dépend de l’environnement et peut modifier la conception.</p>'''),
('validation','Organiser les validations','''<p>Désignez une personne qui centralise les retours. Indiquez qui valide les textes, le design et les fonctionnalités. Un retour regroupé et argumenté évite les décisions contradictoires.</p><p>Pour les sites vitrines THEPEEAK, le délai annoncé est de 48 à 72 heures. Le cadrage précise les contenus nécessaires et le point de départ. Pour une plateforme complexe, le calendrier dépend des règles métier, des intégrations et des validations.</p>'''),
('checklist','Votre brief en huit réponses','''<ol><li>Quelle activité exercez-vous et pour quel public ?</li><li>Quel changement attendez-vous du projet ?</li><li>Que doit pouvoir faire un visiteur ou un utilisateur ?</li><li>Quels contenus et outils existent déjà ?</li><li>Quelles fonctionnalités sont indispensables au lancement ?</li><li>Quelles langues, quels pays et quels moyens de paiement sont concernés ?</li><li>Qui valide et quelles échéances sont importantes ?</li><li>Quelles contraintes de budget, de maintenance ou d’accès faut-il prendre en compte ?</li></ol><p>Vous pouvez aussi joindre des exemples de design en expliquant ce qui vous intéresse : la lisibilité, l’organisation, la sobriété ou une interaction. Une référence aide à se comprendre ; elle ne doit pas être copiée.</p><div class="article-callout"><strong>Inutile d’avoir toutes les réponses pour commencer.</strong><p>Le premier échange sert aussi à clarifier les inconnues et à identifier les décisions à prendre.</p><p><a href="../contact.html?subject=Pr%C3%A9parer%20mon%20projet%20digital">Partager mon brief avec THEPEEAK ↗</a></p></div>''')])]
for slug,title,desc,sections in ARTICLES:
 path='guides/'+slug+'.html';url=BASE+'/'+path
 graph=[breadcrumb_schema(title,url,('Guides','guides/index.html')),{'@type':'Article','headline':title,'description':desc,'datePublished':'2026-10-03','dateModified':'2026-10-03','inLanguage':'fr','author':{'@id':BASE+'/#organization'},'publisher':{'@id':BASE+'/#organization'},'mainEntityOfPage':{'@id':url+'#webpage'}}]
 body=head(title+' | THEPEEAK',desc,path,1,graph)+nav(1)+f'<main id="main"><section class="page-intro"><div class="wrap"><span class="kicker">Guide THEPEEAK · 3 octobre 2026</span><h1>{E(title)}</h1><p class="intro">{E(desc)}</p></div></section><section class="section"><div class="wrap article-layout"><nav class="article-nav" aria-label="Sommaire du guide">'+''.join(f'<a href="#{id}">{E(t)}</a>' for id,t,c in sections)+'</nav><article class="article-body">'+''.join(f'<section id="{id}"><h2>{E(t)}</h2>{c}</section>' for id,t,c in sections)+'</article></div></section></main>'+footer(1)
 (OUT/path).write_text(body)
