export const services = [
  {
    slug: 'web-mobile',
    title: 'Développement Web & Mobile',
    shortDesc: 'Sites vitrines, e-commerce, applications. Des plateformes qui convertissent.',
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&auto=format&fit=crop',
    pain: "Votre business est réel. Mais pour vos clients potentiels, vous n'existez pas.",
    painBody: "En 2025, 82% des consommateurs africains vérifient en ligne avant d'acheter. Si vous n'avez pas de site professionnel, vous perdez ces clients à chaque instant. Vos concurrents, eux, convertissent pendant que vous dormez.",
    stats: '82% des clients cherchent en ligne avant d\'acheter',
    color: '#E8A020',
  },
  {
    slug: 'hebergement',
    title: 'Hébergement & Maintenance',
    shortDesc: 'Hosting premium, mises à jour, sécurité. Votre site protégé 24h/24.',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop',
    pain: "Un site qui tombe, c'est un client perdu — pour toujours.",
    painBody: "Vous avez investi dans un beau site. Mais sans maintenance, sans hébergement fiable, sans mises à jour de sécurité... Un seul incident suffit à effacer des mois de travail et détruire votre crédibilité instantanément.",
    stats: '99.9% uptime garanti',
    color: '#00D4FF',
  },
  {
    slug: 'marketing',
    title: 'Marketing Digital & Créatif',
    shortDesc: 'Logos, visuels, vidéos IA. Une identité qui marque les esprits.',
    image: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&auto=format&fit=crop',
    pain: 'Vous publiez. Vous publiez. Vous publiez. Et personne ne réagit.',
    painBody: "Sans stratégie visuelle cohérente, sans branding professionnel, vos posts se noient dans le flux. Vos concurrents, avec un logo propre et des visuels forts, paraissent 10x plus crédibles. L'image, c'est le premier filtre que vos clients appliquent.",
    stats: '10x plus de crédibilité avec un branding pro',
    color: '#E85D04',
  },
  {
    slug: 'publicite',
    title: 'Campagnes Publicitaires',
    shortDesc: 'Meta Ads & TikTok Ads stratégiques. Des leads qualifiés, pas du bruit.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop',
    pain: "Booster un post ne suffit pas. C'est de l'argent jeté sans stratégie.",
    painBody: "Meta Ads et TikTok Ads sont les leviers les plus puissants pour acquérir des clients à grande échelle en Afrique. Mais mal paramétrées, ces campagnes brûlent votre budget sans générer un seul lead qualifié.",
    stats: '+340% de leads qualifiés en moyenne',
    color: '#2D9E6B',
  },
  {
    slug: 'formation-web',
    title: 'Formation Création de Sites avec IA',
    shortDesc: '3 séances live. Créez et revendez des sites dès la fin de la formation.',
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop',
    pain: "Et si vous pouviez créer des sites à 200 000 FCFA l'unité — même sans savoir coder ?",
    painBody: "En 3 séances live d'1h, vous maîtrisez les outils IA pour créer des plateformes professionnelles. Nos apprenants créent et revendent des sites dès la fin de la formation. C'est une compétence qui se monétise immédiatement.",
    stats: '200 000 FCFA par site revendu',
    color: '#1A5CB5',
  },
]

export const formations = [
  {
    slug: 'print-on-demand',
    title: 'Print On Demand',
    description: 'Lancez votre marque de vêtements sans stock. De zéro à votre première vente en 30 jours.',
    format: 'PDF + Accès immédiat',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop',
    badge: 'Best seller',
    problem: "Vous voulez une marque mais n'avez pas de capital pour du stock ?",
  },
  {
    slug: 'immobilier',
    title: 'Business Immobilier',
    description: 'Investissement immobilier en Afrique. Stratégies concrètes pour un revenu passif.',
    format: 'PDF + Accès immédiat',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&auto=format&fit=crop',
    badge: 'Populaire',
    problem: "Vous voulez investir mais ne savez pas par où commencer ?",
  },
  {
    slug: 'produits-digitaux',
    title: 'Vente de Produits Digitaux',
    description: 'Créez et vendez des e-books, templates, formations. Revenus 100% passifs.',
    format: 'PDF + Accès immédiat',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop',
    badge: 'Nouveau',
    problem: "Vous avez de l'expertise mais ne savez pas la monétiser ?",
  },
  {
    slug: 'musique-ia',
    title: 'Musique & IA',
    description: 'Créez, distribuez et monétisez votre musique avec les outils IA. Sans label.',
    format: 'Live + PDF',
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop',
    badge: 'Live',
    problem: "Vous êtes artiste mais la production coûte trop cher ?",
  },
  {
    slug: 'creation-sites-premium',
    title: 'Création de Sites Premium',
    description: '3 séances live. Maîtrisez les outils IA pour créer des sites et les revendre.',
    format: '3 séances live',
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&auto=format&fit=crop',
    badge: 'Live',
    problem: "Et si vous pouviez facturer 200 000 FCFA par site sans savoir coder ?",
  },
]

export const testimonials = [
  {
    type: 'A',
    name: 'Aminata Kouyaté',
    city: 'Dakar',
    country: 'Sénégal',
    rating: 5,
    text: "J'avais peur de me lancer dans le digital, mais l'équipe Africademia m'a accompagnée pas à pas. Mon site vitrine est magnifique et j'ai déjà eu 3 nouveaux clients en 2 semaines ! Je recommande à 100%.",
    service: 'Site vitrine professionnel',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&auto=format&fit=crop&crop=faces',
    reply: "Merci Aminata ! C'est exactement pour ça qu'on fait ce travail. Continuez sur cette lancée !",
  },
  {
    type: 'C',
    name: 'Marie-Claire N.',
    city: 'Abidjan',
    country: "Côte d'Ivoire",
    rating: 5,
    text: "Depuis la campagne Meta gérée par Africademia, mes demandes de devis ont triplé en 6 semaines.",
    service: 'Campagne Meta Ads',
    metric: '+340% de leads',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&crop=faces',
  },
  {
    type: 'B',
    name: 'Ibrahim Diallo',
    city: 'Bamako',
    country: 'Mali',
    rating: 5,
    text: "La formation Print On Demand a changé ma vie. J'ai lancé ma marque en 30 jours.",
    service: 'Formation Print On Demand',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&crop=faces',
  },
  {
    type: 'A',
    name: 'Fatou Mbaye',
    city: 'Dakar',
    country: 'Sénégal',
    rating: 5,
    text: "Le branding qu'Africademia a créé pour mon restaurant est tout simplement parfait. Mes clients me complimentent sur le logo tous les jours. Professionnalisme et créativité au rendez-vous.",
    service: 'Logo Business',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&crop=faces',
    reply: "Merci Fatou ! Votre restaurant méritait une identité à la hauteur de votre cuisine. Bon vent !",
  },
  {
    type: 'C',
    name: 'Jean-Baptiste Koffi',
    city: 'Cotonou',
    country: 'Bénin',
    rating: 5,
    text: "Mon e-commerce génère maintenant 2x plus de ventes grâce au site Africademia. L'investissement s'est rentabilisé en 3 semaines.",
    service: 'Site E-commerce',
    metric: '+200% de ventes',
    avatar: 'https://images.unsplash.com/photo-1542909168-82c3e7fdcd5f?w=100&auto=format&fit=crop&crop=faces',
  },
  {
    type: 'B',
    name: 'Aïcha Traoré',
    city: 'Ouagadougou',
    country: 'Burkina Faso',
    rating: 5,
    text: "Formation excellente ! En 3 séances j'ai créé mon premier site et j'ai déjà un client.",
    service: 'Formation Création Sites',
    avatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=100&auto=format&fit=crop&crop=faces',
  },
  {
    type: 'A',
    name: 'Moussa Diakité',
    city: 'Paris',
    country: 'France',
    rating: 5,
    text: "Africademia comprend les entrepreneurs africains de la diaspora. Mon site cible à la fois l'Europe et l'Afrique — c'est exactement ce que je voulais. Un travail remarquable.",
    service: 'Site vitrine + SEO',
    avatar: 'https://images.unsplash.com/photo-1504199367641-aba8151af406?w=100&auto=format&fit=crop&crop=faces',
    reply: "Merci Moussa ! La diaspora est un marché clé pour nous. Nous sommes fiers d'avoir capturé votre double ancrage.",
  },
  {
    type: 'C',
    name: 'Nadia Coulibaly',
    city: 'Montréal',
    country: 'Canada',
    rating: 4,
    text: "TikTok Ads géré par Africademia : 0 à 850 abonnés en 15 jours sur mon boutique en ligne.",
    service: 'Campagne TikTok Ads',
    metric: '+850 abonnés',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&auto=format&fit=crop&crop=faces',
  },
]

export const stats = [
  { value: 150, suffix: '+', label: 'Projets réalisés' },
  { value: 98, suffix: '%', label: 'Satisfaction client' },
  { value: 5, suffix: '+', label: 'Services digitaux' },
  { value: 100, suffix: '%', label: 'Accompagnement personnalisé' },
]

export const processSteps = [
  {
    number: '01',
    title: 'DÉCOUVERTE',
    description: 'Consultation offerte. On comprend votre vision et vos besoins.',
    detail: 'On prend le temps de vous écouter, analyser votre marché et définir les objectifs clés.',
  },
  {
    number: '02',
    title: 'CONCEPTION',
    description: 'Maquette gratuite soumise avant tout paiement. Vous validez ou on ajuste.',
    detail: 'Notre équipe créative livre une maquette complète avant tout engagement financier.',
  },
  {
    number: '03',
    title: 'DÉVELOPPEMENT',
    description: 'Développement et mise en ligne selon vos besoins.',
    detail: 'Développement rigoureux avec des mises à jour régulières tout au long du projet.',
  },
  {
    number: '04',
    title: 'LIVRAISON',
    description: 'Vous validez. On assure le support.',
    detail: 'Livraison finale avec formation, documentation et support post-lancement inclus.',
  },
]

export const portfolioProjects = [
  {
    title: 'Boutique Mode Africaine',
    category: 'E-commerce',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop',
    tech: ['Next.js', 'Stripe', 'Tailwind'],
  },
  {
    title: 'Restaurant Saveurs du Sahel',
    category: 'Sites',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&auto=format&fit=crop',
    tech: ['React', 'Framer Motion'],
  },
  {
    title: 'Cabinet Avocat Yaoundé',
    category: 'Sites',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop',
    tech: ['Next.js', 'Tailwind'],
  },
  {
    title: 'App Transport Dakar',
    category: 'Applications',
    image: 'https://images.unsplash.com/photo-1556155092-490a1ba16284?w=800&auto=format&fit=crop',
    tech: ['React Native', 'Node.js'],
  },
  {
    title: 'Campagne Meta Immobilier',
    category: 'Campagnes',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&auto=format&fit=crop',
    tech: ['Meta Ads', 'Créatifs IA'],
  },
  {
    title: 'Identité Agence Digitale',
    category: 'Visuels',
    image: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&auto=format&fit=crop',
    tech: ['Figma', 'Illustrator'],
  },
]

export const blogPosts = [
  {
    slug: 'comment-creer-site-web-africain',
    title: "Comment créer un site web qui convertit en Afrique de l'Ouest",
    excerpt: "Les spécificités du marché africain que tout entrepreneur doit connaître avant de lancer son site.",
    category: 'Digital',
    date: '2026-05-15',
    readTime: '8 min',
    author: 'Équipe Africademia',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop',
  },
  {
    slug: 'meta-ads-afrique-guide',
    title: 'Meta Ads en Afrique : le guide complet 2026',
    excerpt: 'Ciblage, budgets, créatifs — tout ce que vous devez savoir pour des campagnes rentables.',
    category: 'Marketing',
    date: '2026-04-28',
    readTime: '12 min',
    author: 'Équipe Africademia',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop',
  },
  {
    slug: 'ia-business-entrepreneur-africain',
    title: "L'IA au service de l'entrepreneur africain",
    excerpt: 'Les 10 outils IA qui changent la donne pour les PME africaines en 2026.',
    category: 'IA',
    date: '2026-04-10',
    readTime: '6 min',
    author: 'Équipe Africademia',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&auto=format&fit=crop',
  },
]
